modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "militech"
version = "${version}"
displayName = "Militech"
authors = "Me!"
description = '''
Militech.
'''
#logoFile = ""

[[dependencies.militech]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.militech]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.militech]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.militech]]
modId = "playeranimator"
mandatory = true
versionRange = "[1.0.2-rc1+1.20,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.militech]]
modId = "azurelib"
mandatory = true
versionRange = "[3.1.11,)"
ordering = "AFTER"
side = "BOTH"
