package com.xirc.militech.datagen.providers.assets;

import com.xirc.militech.Militech;
import com.xirc.militech.registry.MilitechItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.models.BlockModelGenerators;
import net.minecraft.data.models.ItemModelGenerators;
import net.minecraft.data.models.model.ModelLocationUtils;
import net.minecraft.data.models.model.ModelTemplates;
import net.minecraft.data.models.model.TextureMapping;
import net.minecraft.world.item.Item;

public class MilitechModelProvider extends FabricModelProvider {

    public MilitechModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators generator) {
        // No blocks to generate yet.
    }

    @Override
    public void generateItemModels(ItemModelGenerators generator) {
        // Flat ammo rounds and ammo boxes. Textures live in subdirectories under
        // textures/item/, so the flat item model is generated by hand instead of
        // generator.generateFlatItem(), which only knows the item's own registry path.
        // Guns use hand-authored builtin/entity models and are not generated here.
        generateFlatItem(generator, MilitechItems.PISTOL_ROUND.get(), "item/bullet/pistol/pistol_round");
        generateFlatItem(generator, MilitechItems.RIFLE_ROUND.get(), "item/bullet/rifle_round");
        generateFlatItem(generator, MilitechItems.SHOTGUN_SHELL.get(), "item/bullet/shotgun/shotgun_shell");
        generateFlatItem(generator, MilitechItems.PISTOL_BOX.get(), "item/storage/pistol_box");
        generateFlatItem(generator, MilitechItems.RIFLE_BOX.get(), "item/storage/rifle_box");
        generateFlatItem(generator, MilitechItems.SHOTGUN_BOX.get(), "item/storage/shotgun_box");
        generateFlatItem(generator, MilitechItems.FRAME.get(), "item/crafting/frame");
        generateFlatItem(generator, MilitechItems.BARREL.get(), "item/crafting/barrel");
        generateFlatItem(generator, MilitechItems.MECHANISM.get(), "item/crafting/mechanism");
        generateFlatItem(generator, MilitechItems.COMPONENT.get(), "item/crafting/component");
        generateFlatItem(generator, MilitechItems.MAGAZINE.get(), "item/storage/magazine");
    }

    private static void generateFlatItem(ItemModelGenerators generator, Item item, String texturePath) {
        ModelTemplates.FLAT_ITEM.create(
                ModelLocationUtils.getModelLocation(item),
                TextureMapping.layer0(Militech.id(texturePath)),
                generator.output
        );
    }
}
