package com.xirc.milicraft.datagen.providers.assets;

import com.xirc.milicraft.Milicraft;
import com.xirc.milicraft.registry.MilicraftItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricModelProvider;
import net.minecraft.data.models.BlockModelGenerators;
import net.minecraft.data.models.ItemModelGenerators;
import net.minecraft.data.models.model.ModelLocationUtils;
import net.minecraft.data.models.model.ModelTemplates;
import net.minecraft.data.models.model.TextureMapping;
import net.minecraft.world.item.Item;

public class MilicraftModelProvider extends FabricModelProvider {

    public MilicraftModelProvider(FabricDataOutput output) {
        super(output);
    }

    @Override
    public void generateBlockStateModels(BlockModelGenerators generator) {
        // No blocks to generate yet.
    }

    @Override
    public void generateItemModels(ItemModelGenerators generator) {
        // Flat ammo rounds and ammo boxes. Textures live in subdirectories under
        // textures/item/, so the flat item model is generated by hand instead of
        // generator.generateFlatItem(), which only knows the item's own registry path.
        // Guns use hand-authored builtin/entity models and are not generated here.
        generateFlatItem(generator, MilicraftItems.PISTOL_ROUND.get(), "item/bullet/pistol/pistol_round");
        generateFlatItem(generator, MilicraftItems.RIFLE_ROUND.get(), "item/bullet/rifle_round");
        generateFlatItem(generator, MilicraftItems.SHOTGUN_SHELL.get(), "item/bullet/shotgun/shotgun_shell");
        generateFlatItem(generator, MilicraftItems.PISTOL_BOX.get(), "item/storage/pistol_box");
        generateFlatItem(generator, MilicraftItems.RIFLE_BOX.get(), "item/storage/rifle_box");
        generateFlatItem(generator, MilicraftItems.SHOTGUN_BOX.get(), "item/storage/shotgun_box");
        generateFlatItem(generator, MilicraftItems.FRAME.get(), "item/crafting/frame");
        generateFlatItem(generator, MilicraftItems.BARREL.get(), "item/crafting/barrel");
        generateFlatItem(generator, MilicraftItems.MECHANISM.get(), "item/crafting/mechanism");
        generateFlatItem(generator, MilicraftItems.COMPONENT.get(), "item/crafting/component");
        generateFlatItem(generator, MilicraftItems.MAGAZINE.get(), "item/storage/magazine");
    }

    private static void generateFlatItem(ItemModelGenerators generator, Item item, String texturePath) {
        ModelTemplates.FLAT_ITEM.create(
                ModelLocationUtils.getModelLocation(item),
                TextureMapping.layer0(Milicraft.id(texturePath)),
                generator.output
        );
    }
}
